09_laravel_tdd/project/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('/comments', App\Http\Controllers\CommentController::class);

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

Route::resource('/history', App\Http\Controllers\Shopping\HistoryController::class)->middleware('auth');

Route::resource('/generate', App\Http\Controllers\Shopping\GenerateController::class)->middleware('auth');

Route::resource('/shoppingList', App\Http\Controllers\Shopping\ShoppingListController::class)->middleware('auth');
Route::resource('shoppingList.product',App\Http\Controllers\Shopping\ProductController::class)->middleware('auth');

09_laravel_tdd/project/app/Http/Controllers/Shopping/GenerateController.php
<?php

namespace App\Http\Controllers\Shopping;

use App\Http\Controllers\Controller;
use App\Models\Product;
use App\Models\ProductFrequency;
use App\Models\ShoppingList;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Carbon;

class GenerateController extends Controller
{
    public function index()
    {
        $shoppingList = $this->fetch_data();
        //return view('shopping.shoppingList.index')->withShoppingList($shoppingList);
        return redirect()->route('shoppingList.index');

    }

    public function calculate_frequency($item, $user_id)
    {
        $lists = ShoppingList::where('user_id', $user_id)->whereHas('products', function (Builder $query) use ($item) {
            $query->where('product', $item);
        })->get();
        $dates = array();
        foreach($lists as $list)
        {
            array_push($dates, $list->created_at);
        }
        if(count($dates) < 2)
        {
            return -1;
        }
        asort($dates);

        $diff = $dates[0];
        $avg = 0;
        for($i=1; $i<count($dates); $i++)
        {
            $avg += ($diff->diffInDays($dates[$i]));
            $diff = $dates[$i];
        }
        $avg /= (count($dates)-1);
        return $avg;
    }

    public function fetch_data()
    {
        $user_id = Auth::id(); //get the id of currently logged in user

        $product_frequencies = ProductFrequency::where('user_id', $user_id)->get();
        foreach($product_frequencies as $fr) {
            if ($fr->fr_manually_added == 0) {
                $new_frequency = $this->calculate_frequency($fr->product, $user_id);
                if($new_frequency != -1) {
                    ProductFrequency::where('user_id', $user_id)->where('product', $fr->product)->update(['frequency' => $new_frequency]);
                }
            }
        }
        return $this->generate_list($user_id);

    }

    public function generate_list($user_id)
    {
        $shopping_list = new ShoppingList();
        $shopping_list->user_id = $user_id;
        $shopping_list->done = false;
        $shopping_list->save();
        //function calculating what the user should currently buy, based on frequencies and current date

        $mytime = Carbon::now()->toDateTimeString(); //current time
        $products = ProductFrequency::where('user_id', $user_id)->get(); //products of current user

        foreach($products as $product) {
            $product_name = $product->product;

            // querying the created_time of the latest list which contains product checked in this loop iteration
                 $list = ShoppingList::where('user_id', $user_id)->whereHas('products', function (Builder $query) use ($product_name) {
                    $query->where('product', $product_name);
                })->latest()->get();
                 $list_count = $list->count();
                $product_fr_man = ProductFrequency::where('user_id', $user_id)->where('product', $product_name)->first();

                 if($list_count < 2 && $product_fr_man->fr_manually_added == 0)
                 {
                     continue;
                 }

            $date = $list[0]->created_at;
            if(($date->addDays($product->frequency)) <= $mytime)
            {
                $prod_freq = Auth::user()->frequencies->where('product', $product_name)->first();
                $prod_freq->is_bought = false;
                $prod_freq->save();
                $prod_to_connect = Product::where('product', $product_name)->first();
                $shopping_list->products()->attach($prod_to_connect->id,['shopping_list_id' => $shopping_list->id]);
            }
        }

        return $shopping_list;
    }
}

09_laravel_tdd/project/app/Http/Controllers/Shopping/HistoryController.php
<?php

namespace App\Http\Controllers\Shopping;

use App\Http\Controllers\Controller;
use App\Models\ShoppingList;
use App\Models\Product;
use App\Models\ProductFrequency;
use App\Models\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;


class HistoryController extends Controller
{
    public function index()
    {
        $user_id = Auth::id();
        $listsCount = ShoppingList::where('user_id', $user_id)->where('done',true)->get()->count();
        if($listsCount>0) {
            $shoppingLists = ShoppingList::where('user_id', $user_id)->where('done',true)->latest()->get();
            return view('shopping.history.index')->withShoppingLists($shoppingLists);
        }
        else{
            return view('shopping.history.index')->withShoppingLists(NULL);
        }
    }

    public function show($shoppingListId)
    {
        $shoppingList = ShoppingList::find($shoppingListId);
        return view('shopping.history.show')->withShoppingList($shoppingList);
    }

    public function destroy($shoppingListId)
    {
        $shoppingList = ShoppingList::find($shoppingListId);
        foreach ($shoppingList->products as $product) {
            $user_lists = Auth::user()->lists;
            $user_lists = $user_lists->map( function($value, $key) use ($product){
                $collection = $value->products->where('product', $product->product);
                return $collection;
            });
            if($user_lists->flatten()->count() < 2) {
                $product_frequency = ProductFrequency::where('user_id', Auth::id())->where('product', $product->product)->first();
                $product_frequency->delete();
                if(!ProductFrequency::where('product', $product->product)->first())
                {
                    $product->delete();
                }
            }
        }
        $shoppingList->delete();

        return redirect()->route('history.index');
    }
}

09_laravel_tdd/project/app/Http/Controllers/Shopping/ProductController.php
<?php

namespace App\Http\Controllers\Shopping;
use App\Http\Controllers\Controller;
use App\Models\Product;
use App\Models\ProductFrequency;
use App\Models\ShoppingList;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;


class ProductController extends Controller
{
    public function store(Request $request, ShoppingList $shoppingList)
    {
        $this->validate($request, [
            'product' => 'required',
            'frequency' => 'numeric|nullable'
        ]);

        $frequency = ProductFrequency::where('user_id', Auth::id())->where('product', $request->product)->first();
        if (!$frequency) {
            $frequency = new ProductFrequency();
            $frequency->user_id = Auth::id();
        }
        if ($request->frequency != "") {
            $frequency->frequency = $request->frequency;
            $frequency->fr_manually_added = true;
        } else {
            $frequency->fr_manually_added = false;
            $frequency->frequency = 0;
        }
        $frequency->product = $request->product;
        $frequency->save();


        $product = Product::where('product', $request->product)->first();

        if (!$product) {
            $product = new Product();
            $product->product = $request->product;
            $product->save();
        }
        if ($shoppingList->products->contains($product) == false) {
            $shoppingList->products()->attach($product->id, ['shopping_list_id' => $shoppingList->id]);
        }
        return redirect()->route('shoppingList.index');
    }

    public function create(ShoppingList $shoppingList)
    {
        return view('shopping.shoppingList.create')->withShoppingList($shoppingList);
    }
}

09_laravel_tdd/project/app/Http/Controllers/Shopping/ShoppingListController.php
<?php


namespace App\Http\Controllers\Shopping;

use App\Models\Product;
use App\Models\ProductFrequency;
use App\Models\ShoppingList;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ShoppingListController extends Controller
{
    public function index()
    {
        $shoppingList = ShoppingList::where('user_id',Auth::id())->where('done',false)->latest()->first();
        $boughtItems = array();
        if($shoppingList) {
            $boughtItems = $shoppingList->products;
            $productFreq = Auth::user()->frequencies;
            $boughtItems = $boughtItems->map(function ($value, $key) use ($productFreq) {
                $collection = $productFreq->where('product', $value->product)->where('is_bought', true);
                return $collection;
            });
            $boughtItems = $boughtItems->flatten();
            $items = $shoppingList->products->count();
            if ($boughtItems->count() == $items && $items > 0) {
                $shoppingList->done = true;
                $shoppingList->save();
            }
        }

        return view("shopping.shoppingList.index",['boughtItems' => $boughtItems])->withShoppingList($shoppingList);
    }

    public function create()
    {
        $shoppingList = new ShoppingList();
        $shoppingList->user_id = Auth::id();
        $shoppingList->done = false;
        $productFreq = Auth::user()->frequencies;
        foreach( $productFreq as $product){
            $product->is_bought = false;
            $product->save();
        }
        $shoppingList->save();

        return redirect()->route('shoppingList.index');
    }

    public function update(ShoppingList $shoppingList, Request $request)
    {
        foreach ($shoppingList->products as $product)
        {
            $freq = ProductFrequency::where('user_id',Auth::id())->where('product',$product->product)->first();
            if ($request->input('checkbox'.$product->id) == 'on')
            {
                $freq->is_bought = true;
                $freq->save();
            }
        }
        return redirect()->route('shoppingList.index');
    }



}

09_laravel_tdd/project/app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

09_laravel_tdd/project/resources/views/shopping/history/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight bg-green-100 rounded-lg">
            {{ __('Shopping history') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-green-100 overflow-hidden shadow-sm sm:rounded-lg">

                @if($shoppingLists == NULL)
                    <p class="p-6">You have no shopping lists.</p>
                @else
                    <table class="min-w-full divide-y divide-gray-200">
                        <thead class="bg-green-100">
                        <tr>
                            <th scope="col"
                                class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Created at
                            </th>

                            <th scope="col" class="relative px-6 py-3">
                                <span class="sr-only">Details</span>
                            </th>
                        </tr>
                        </thead>
                        <tbody class="bg-green-50 divide-y divide-gray-200">
                        @foreach($shoppingLists as $shoppingList)
                            <tr>
                                <td class="px-6 py-4 whitespace-nowrap">
                                    <div class="text-sm text-gray-500">{{ $shoppingList->created_at }}</div>
                                </td>

                                <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                    <a href="{{ route('history.show',  $shoppingList ) }}" class="text-indigo-600 hover:text-indigo-900">Details</a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                @endif


            </div>
        </div>
    </div>
</x-app-layout>

09_laravel_tdd/project/resources/views/shopping/history/show.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight bg-green-100 rounded-lg">
            {{ __('Viewing a shopping list created at ' . $shoppingList->created_at) }}
        </h2>
    </x-slot>
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">

            <div class="bg-green-100 shadow overflow-hidden sm:rounded-lg">
                <div class="bg-green-100 px-4 py-5 pb-5 flex items-center justify-end mt-4 sm:grid sm:grid-cols-3 sm:px-6">

                    <div class="w-full sm:max-w-md mt-6 px-6 py-4 bg-green-50 shadow-md overflow-hidden sm:rounded-lg">

                        <p class="p-6">Products:</p>
                        @foreach ($shoppingList->products as $product)
                            <li>
                                {{ $product->product }}
                            </li>
                        @endforeach

                    </div>

                    <form method="post" action="{{ route('history.destroy', $shoppingList) }}">

                        @csrf
                        @method("DELETE")

                        <x-button class="ml-4">
                            {{ __('Delete') }}
                        </x-button>
                    </form>

                </div>
            </div>

        </div>
    </div>

</x-app-layout>