09_laravel_tdd/project/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('/comments', App\Http\Controllers\CommentController::class);

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

Route::resource('/history', App\Http\Controllers\Shopping\HistoryController::class)->middleware('auth');

Route::resource('/generate', App\Http\Controllers\Shopping\GenerateController::class)->middleware('auth');

Route::resource('/shoppingList', App\Http\Controllers\Shopping\ShoppingListController::class)->middleware('auth');
Route::resource('shoppingList.product',App\Http\Controllers\Shopping\ProductController::class)->middleware('auth');

09_laravel_tdd/project/app/Models/Comment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    use HasFactory;
}

09_laravel_tdd/project/app/Http/Controllers/CommentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Comment;
use Illuminate\Http\Request;

class CommentController extends Controller
{
    public function index()
    {
        $comments = Comment::all();
        return view('comments.index')->withComments($comments);
    }

    public function show(Comment $comment)
    {
        return view('comments.show')->withComment($comment);
    }
}

09_laravel_tdd/project/app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

09_laravel_tdd/project/resources/views/comments/index.blade.php
<x-guest-layout>
    <div class="min-h-screen flex flex-col sm:justify-center items-center pt-6 sm:pt-0 bg-gray-100">
        <div>
            Comments
        </div>

        <div class="w-full sm:max-w-md mt-6 px-6 py-4 bg-white shadow-md overflow-hidden sm:rounded-lg">
            @foreach ($comments as $comment)
                <li>
                    <a href="/comments/{{ $comment->id }}">{{ $comment->title }}</a>
                </li>
            @endforeach
        </div>
    </div>
</x-guest-layout>

09_laravel_tdd/project/resources/views/comments/show.blade.php
<x-guest-layout>
    <div class="min-h-screen flex flex-col sm:justify-center items-center pt-6 sm:pt-0 bg-gray-100">
        <h1>
            {{ $comment->title }}
        </h1>

        <div class="w-full sm:max-w-md mt-6 px-6 py-4 bg-white shadow-md overflow-hidden sm:rounded-lg">
            @markdown($comment->text)
        </div>
    </div>
</x-guest-layout>